apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-ingress
  namespace: sre-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sre-go.<PUBLIC_IP>.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-go
                port:
                  number: 80
    - host: sre-node.<PUBLIC_IP>.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-node
                port:
                  number: 80
